# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            JoongWon SHIN
tagline:          'CV / Timeline'
description:      'SNU CSE 22. Seoul National University, B.S. in Computer Science and Engineering.'
url: "https://joongwon0204.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge
permalink: pretty

paginate:         10

# Custom vars

github:
  repo:           https://github.com/joongwon0204
