# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            JoongWon SHIN
tagline:          'CV / Timeline'
description:      'SNU CSE'
url:              "https://joongwon0204.github.io"
baseurl:          "https://joongwon0204.github.io"

markdown: kramdown
highlighter: rouge
permalink: pretty

paginate:         5

# Custom vars

github:
  repo:           https://github.com/joongwon0204/
